import type { RequestCardProps } from "@/src/components/ui/request-card/request-card.types";

export const MOCK_REQUESTS: Omit<RequestCardProps, "onAccept" | "onReject" | "onViewDossier" | "className">[] = [
  {
    id: "req-001",
    protocol: "REP-2024-891",
    citizenName: "Carlos Souza",
    area: "Direito Trabalhista",
    status: "pending",
    createdAt: "15/03/2024",
  },
  {
    id: "req-002",
    protocol: "REP-2024-892",
    citizenName: "Maria Fernanda Costa",
    area: "Direito Civil",
    status: "pending",
    createdAt: "14/03/2024",
  },
  {
    id: "req-003",
    protocol: "REP-2024-893",
    citizenName: "João Pedro Almeida",
    area: "Direito de Família",
    status: "accepted",
    createdAt: "13/03/2024",
  },
  {
    id: "req-004",
    protocol: "REP-2024-894",
    citizenName: "Ana Beatriz Lima",
    area: "Direito do Consumidor",
    status: "accepted",
    createdAt: "12/03/2024",
  },
  {
    id: "req-005",
    protocol: "REP-2024-895",
    citizenName: "Roberto Martins",
    area: "Direito Previdenciário",
    status: "rejected",
    createdAt: "11/03/2024",
  },
  {
    id: "req-006",
    protocol: "REP-2024-896",
    citizenName: "Patrícia Oliveira",
    area: "Direito Trabalhista",
    status: "pending",
    createdAt: "10/03/2024",
  },
  {
    id: "req-007",
    protocol: "REP-2024-897",
    citizenName: "Fernando Ribeiro",
    area: "Direito Imobiliário",
    status: "rejected",
    createdAt: "09/03/2024",
  },
];
