export const PASSWORD_MIN_LENGTH = 8;

export const passwordChecks = [
  {
    id: "length",
    label: "8+ chars",
    test: (value: string) => value.length >= PASSWORD_MIN_LENGTH,
  },
  {
    id: "uppercase",
    label: "Maiúscula",
    test: (value: string) => /[A-ZÀ-Ý]/.test(value),
  },
  {
    id: "symbol",
    label: "Símbolo",
    test: (value: string) => /[^\p{L}\p{N}\s]/u.test(value),
  },
] as const;

export const heroHighlights = [
  {
    title: "Novas Oportunidades",
    description:
      "Acesso direto a demandas qualificadas e aumente significativo do seu networking profissional.",
  },
  {
    title: "Agilidade Digital",
    description:
      "Resolva pendências jurídicas com a velocidade que o mundo moderno exige.",
  },
] as const;

export const specializationOptions = [
  { value: "Administrative", label: "Direito Administrativo" },
  { value: "BankingAndFinancial", label: "Direito Bancário e Financeiro" },
  { value: "Business", label: "Direito Empresarial" },
  { value: "Civil", label: "Direito Civil" },
  { value: "Competition", label: "Direito da Concorrência" },
  { value: "Constitutional", label: "Direito Constitucional" },
  { value: "Consumer", label: "Direito do Consumidor" },
  { value: "Contract", label: "Direito dos Contratos" },
  { value: "Criminal", label: "Direito Penal" },
  { value: "CriminalDefense", label: "Defesa Criminal" },
  { value: "Digital", label: "Direito Digital" },
  { value: "Electoral", label: "Direito Eleitoral" },
  { value: "Employment", label: "Direito do Trabalho" },
  { value: "Environmental", label: "Direito Ambiental" },
  { value: "EstatePlanning", label: "Planejamento Sucessório" },
  { value: "FamilyAndInheritance", label: "Direito de Família e Herança" },
  { value: "ForeignTrade", label: "Comércio Exterior" },
  { value: "HealthLaw", label: "Direito da Saúde" },
  { value: "Housing", label: "Direito Habitacional" },
  { value: "HumanRights", label: "Direitos Humanos" },
  { value: "ImmigrationAndRefugee", label: "Imigração e Refugiados" },
  { value: "IndigenousLaw", label: "Direito Indígena" },
  { value: "InsolvencyAndBankruptcy", label: "Insolvência e Falência" },
  { value: "Insurance", label: "Direito de Seguros" },
  { value: "IntellectualProperty", label: "Propriedade Intelectual" },
  { value: "InternationalLaw", label: "Direito Internacional" },
  { value: "JudicialReview", label: "Controle Judicial" },
  { value: "LandUse", label: "Uso do Solo" },
  { value: "LaborAndEmployment", label: "Trabalhista e Empregatício" },
  { value: "MediaAndEntertainment", label: "Mídia e Entretenimento" },
  { value: "MedicalMalpractice", label: "Erro Médico" },
  { value: "MilitaryLaw", label: "Direito Militar" },
  { value: "Mining", label: "Direito Minerário" },
  { value: "NotaryAndRegistry", label: "Notarial e Registral" },
  { value: "PharmaceuticaLaw", label: "Direito Farmacêutico" },
  { value: "PoliticsAndLegislation", label: "Política e Legislação" },
  { value: "PrivacyLaw", label: "Direito à Privacidade" },
  { value: "ProductLiability", label: "Responsabilidade de Produto" },
  { value: "PublicProcurement", label: "Licitações e Contratos Públicos" },
  { value: "RealEstate", label: "Direito Imobiliário" },
  { value: "RegulatoryCompliance", label: "Compliance e Regulatório" },
  { value: "Securities", label: "Mercado de Capitais" },
  { value: "SocialSecurity", label: "Previdência Social" },
  { value: "SportLaw", label: "Direito Desportivo" },
  { value: "StartupAndInnovation", label: "Startups e Inovação" },
  { value: "Tax", label: "Direito Tributário" },
  { value: "Technology", label: "Direito de Tecnologia" },
  { value: "Telecommunications", label: "Telecomunicações" },
  { value: "TrustAndBanking", label: "Fiduciário e Bancário" },
  { value: "Utility", label: "Serviços de Utilidade Pública" },
  { value: "WorkersCompensation", label: "Indenização Trabalhista" },
] as const;

export const brazilianStates = [
  { value: "AC", label: "AC" },
  { value: "AL", label: "AL" },
  { value: "AP", label: "AP" },
  { value: "AM", label: "AM" },
  { value: "BA", label: "BA" },
  { value: "CE", label: "CE" },
  { value: "DF", label: "DF" },
  { value: "ES", label: "ES" },
  { value: "GO", label: "GO" },
  { value: "MA", label: "MA" },
  { value: "MT", label: "MT" },
  { value: "MS", label: "MS" },
  { value: "MG", label: "MG" },
  { value: "PA", label: "PA" },
  { value: "PB", label: "PB" },
  { value: "PR", label: "PR" },
  { value: "PE", label: "PE" },
  { value: "PI", label: "PI" },
  { value: "RJ", label: "RJ" },
  { value: "RN", label: "RN" },
  { value: "RS", label: "RS" },
  { value: "RO", label: "RO" },
  { value: "RR", label: "RR" },
  { value: "SC", label: "SC" },
  { value: "SP", label: "SP" },
  { value: "SE", label: "SE" },
  { value: "TO", label: "TO" },
] as const;
